# Generated by Django 3.2.4 on 2021-07-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0006_auto_20210719_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='genre',
            field=models.CharField(blank=True, choices=[('メニュー', 'メニュー'), ('その他', 'その他')], max_length=200, null=True, verbose_name='ジャンル'),
        ),
    ]
