# Generated by Django 3.2.4 on 2021-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museum', '0007_post_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text2',
            field=models.TextField(blank=True, default='本文2', max_length=100000, null=True),
        ),
    ]
